apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: registry.digitalocean.com/graders-3es/backend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
      imagePullSecrets:
      - name: graders-3es
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "03da62ec-47d2-4a7b-90d8-fb06a73ab2c5"
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  selector:
    app: backend
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    cert-manager.io/cluster-issuer: letsencrypt-prod
#spec:
#  tls:
#  - hosts:
##    - 3es.bhendel.io
#    secretName: hello-kubernetes-tls
#  rules:
#  - host: "3es.bhendel.io"
#    http:
#      paths:
#      - pathType: Prefix
#        path: "/"
#        backend:
#          service:
#            name: frontend-service
#            port:
#              number: 80
#      - pathType: Prefix
#        path: "/api"
#        backend:
#          service: