name: Automated Pull-Request

on:
  push:
    branches-ignore: ["main"]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Automated Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                              
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: |                                       
           *An automated PR*
        pr_template: ".github/templates/pull_request_template.md"
        pr_assignee: "${{ github.actor }}"
        pr_label: "auto-pr"                              
        pr_draft: true                                    
        pr_allow_empty: false         
        github_token: ${{ secrets.ACCESS_TOKEN_GRADERS }}      
